### ISSUE TITLE
Keep license info from original code

### ISSUE THREAD

**Issue by markzhai** [seiginonakama/BlockCanaryEx#1]
According to Apache license, you should keep the original license info from the code, like what I do to https://github.com/lqcandqq13/BlockCanaryEx/blob/master/BlockCanaryExJRT/src/main/java/com/letv/sarrsdesktop/blockcanaryex/jrt/ui/DisplayActivity.java, you can notice even I modify most of the code, I still keep the Square license there, what is missing in some of your code like https://github.com/lqcandqq13/BlockCanaryEx/blob/master/BlockCanaryExJRT/src/main/java/com/letv/sarrsdesktop/blockcanaryex/jrt/BlockInfo.java

Also, what you do in `LooperMonitor.java`:
```java
if(x.startsWith(">")) {
```
is not a good idea, as String compare it not that good for performance, you should be able to find a better way in my code.

**Comment by seiginonakama** [comment]
Thank you for reminding me。I added the origin license to the modified code just now and hope you check it again. I am a freshman of open source but I will pay more attention to the license from now. Thank you again.

you are right about what I do in LooperMonitor.java:
```java
   if(x.startsWith(">")) {
```
it's not good for performance.

I missed the detail that looper's printer can't be change when dispatching, and it always call printer.print() first from the begin of dispatching once the printer was set, so use mPrintingStarted is always right.
 
Thank you for you advice.
