### ISSUE TITLE
Error:A problem occurred configuring project ':app'.

### ISSUE THREAD

**Issue by CyrusCeasar** [seiginonakama/BlockCanaryEx#13]
ide: as 3.0 Canary1 环境，使用kotlin进行开发时遇到的。
当我把这句 apply plugin: 'blockcanaryex' 添加到 module下面的build.gradle时 ，会报
Error:A problem occurred configuring project ':app'.
错误日志比较长，我保存到文件里，不知道哪句对您解决问题有帮助。如果需要更详细的信息，请告知我。
[错误日志.docx](https://github.com/seiginonakama/BlockCanaryEx/files/1016598/default.docx)

**Comment by seiginonakama** [comment]
@CyrusCeasar 谢谢你的log。
```
if(!transform.getClass().getCanonicalName().startsWith("com.android.build.gradle.internal.transforms")) {
                    ......
        }
```
问题出在gradle-core-3.0.0-alpha1.jar的TransformManager这个地方，局部类和匿名类getCanonicalName()这个函数都是返回为空的，而android没有判空。。所以严谨来说应该是android的bug。

**Comment by seiginonakama** [comment]
下个版本我兼容一下吧，改好了告诉你。

**Comment by CyrusCeasar** [comment]
好的，期待ing

**Comment by seiginonakama** [comment]
@CyrusCeasar 请尝试一下以下版本，这个plugin版本修复了这个问题
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.letv.sarrsdesktop:BlockCanaryExPlugin:0.9.9.2'
    }
}
```

**Comment by CyrusCeasar** [comment]
@seiginonakama  it works
