### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by pangli** [seiginonakama/BlockCanaryEx#2]
![image](https://cloud.githubusercontent.com/assets/7498978/24193658/0ad1bf84-0f2e-11e7-8158-8248dbf02468.png)

**Comment by seiginonakama** [comment]
@pangli 
看图应该是网络问题，或者是没有添加jcenter库
1. 请检查一下你的网络是否有问题
2. 检查一下项目根目录下的build.grade是否有添加jcenter
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0' //version must >= 1.5.0
        classpath 'com.letv.sarrsdesktop:BlockCanaryExPlugin:0.9.4'
    }
}

**Comment by pangli** [comment]
已经添加了，在另一个项目中添加成功了，但是截图这个项目中添加不成功，网络正常，我也很奇怪，一个项目能添加正常，一个就不正常

**Comment by pangli** [comment]
原来在这个地方忘记写了
![image](https://cloud.githubusercontent.com/assets/7498978/24228592/350a167a-0fb0-11e7-910a-e7a8c464a33d.png)
但是又出现了新的问题
![image](https://cloud.githubusercontent.com/assets/7498978/24228679/b621b038-0fb0-11e7-9830-45ba1102ff99.png)

**Comment by seiginonakama** [comment]
你可以看下这个问题 https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/365

**Comment by pangli** [comment]
是的就是这个问题，好了，谢谢了
