### ISSUE TITLE
使用MultiDex.install(this)后, 编译通过, 但项目运行不起来

### ISSUE THREAD

**Issue by LLhon** [seiginonakama/BlockCanaryEx#23]
继承MultiDexApplication, 
版本: 0.9.9.5

**Comment by seiginonakama** [comment]
运行不起来什么意思？android运行时报错么？还是说apk已经编译出来了，安装不上？

**Comment by LLhon** [comment]
app启动失败, 一进欢迎页面就闪退了.

**Comment by seiginonakama** [comment]
@LLhon 如果可以请把报错堆栈贴上来，谢谢。

**Comment by seiginonakama** [comment]
我测试过在BlockCanaryExJRT 0.9.9.4版本上是没啥问题的，你可以检查一下版本
```groovy
debugCompile 'com.letv.sarrsdesktop:BlockCanaryExJRT:0.9.9.4'
releaseCompile 'com.letv.sarrsdesktop:BlockCanaryExJRTNoOp:0.9.9.4'
testCompile 'com.letv.sarrsdesktop:BlockCanaryExJRTNoOp:0.9.9.4'
```

**Comment by LLhon** [comment]
嗯谢谢, 貌似有些第三方库放在attachBaseContext()里会报错, 像友盟的推送库报错了Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.content.Context.getMainLooper()' on a null object reference
我把第三方库的初始化都放在onCreate()里就没问题啦
