### ISSUE TITLE
0.9.5 类型转换有误

### ISSUE THREAD

**Issue by jp1017** [seiginonakama/BlockCanaryEx#3]
<img src="https://cloud.githubusercontent.com/assets/7868514/24281261/198d7094-1092-11e7-91ee-94b446c3fd40.png" width="320"/>

**Comment by seiginonakama** [comment]
喔。看来你的工程即引用了BlockCanary，又使用了BlockCanaryEx。
因为BlockCanaryEx的资源文件直接从BlockCanary搬过来的，所以如果同时引用了这俩会造成资源文件冲突。
我刚才修改了一下BlockCanaryEx的资源文件名，你使用0.9.5.1版本试一下。

**Comment by jp1017** [comment]
0.9.5.1 works well. 😄 👍 @lqcandqq13
