### ISSUE TITLE
javassist.NotFoundException: android.content.pm.IPackageStatsObserver$Stub

### ISSUE THREAD

**Issue by tonycheng93** [seiginonakama/BlockCanaryEx#8]
Error:Execution failed for task :SkyMoviePlatform5.5:transformClassesWithBlockCanaryExFor_defaultDebug'.
> javassist.NotFoundException: android.content.pm.IPackageStatsObserver$Stub
出现这个问题，然后我进行了下面的配置：

```java
block {
    debugEnabled true //在debug模式下开启方法采样，默认为true
    releaseEnabled false //在release模式下开启方法采样，默认为false
    excludePackages = ['com.android', 'android.support','android.content'] //不希望进行方法采样的包名, 比如: ['com.android', 'android.support']
    excludeClasses = ['android.content.pm.IPackageStatsObserver'] //不希望进行方法采样的类名
//    includePackages [] //指定开启方法采样的包名，如果不为空，则其它没有包括进来的包都不会开启方法采样

    scope {
        project true //开启主项目代码方法采样，默认为true
        projectLocalDep false //开启主项目本地libs代码(比如.jar)方法采样，默认为false,
        subProject true //开启子项目代码方法采样，默认为true
        subProjectLocalDep false //开启子项目本地libs方法采样，默认为false
        externalLibraries false //开启第三方libs方法采样，默认为false
    }
}
```

把这个类`android.content.pm.IPackageStatsObserver`排除了，还是不行

**Comment by seiginonakama** [comment]
IPackageStatsObserver这个类实际上是隐藏的吧？代码里有用到这个类么？怎么使用这个类的？

**Comment by seiginonakama** [comment]
另外希望给出一些详细的信息，比如compile sdk version，com.android.tools.build:gradle version等

**Comment by tonycheng93** [comment]
确实有方法调用了IPackageStatsObserver，但是这个方法没有被调用，然后我把它注释了，但是现在出现了另外一个问题：
```
Error:Execution failed for task ':SkyMoviePlatform5.5:transformClassesWithBlockCanaryExFor_defaultDebug'.
> javassist.CannotCompileException: cannot find android.content.res.ConstantState
```
`android.content.res.ConstantState`位于`layoutlib.jar`,我设置的是不开启本地`libs`方法采样。
项目的一些信息如下：
`gradle:2.2.2`
`buildTools:23.0.3`
`compile sdk:23`

**Comment by seiginonakama** [comment]
这个也是android的隐藏类，你是通过provide jar包的方式来访问这些android隐藏类吧?我一会也这样试试。

**Comment by tonycheng93** [comment]
嗯嗯，对，是通过provide的方式访问的，如果我把`subProject true //开启子项目代码方法采样，默认为true`置为`false`就不会有问题，但是我现在希望的是开启子项目代码采样

**Comment by seiginonakama** [comment]
@tonycheng93 问题出在javaassit的classpath 没有引入provide的jar路径，0.9.8.3已经解决了，你试试。

**Comment by tonycheng93** [comment]
@seiginonakama 非常感谢作者，0.9.8.2版本可以正常使用，最近刚好在做性能优化方面的工作，看到作者的这个库很有帮助，十分感谢！

**Comment by seiginonakama** [comment]
@tonycheng93 不客气，谢谢你的issue，我以前还没注意到这个。其实0.9.8.3才是完美解决，0.9.8.2不能兼容library工程里的provide依赖。。

**Comment by tonycheng93** [comment]
@seiginonakama 我的library里面没有provide依赖，所以更新了你的0.9.8.2就可以解决我的问题了

**Comment by seiginonakama** [comment]
resolved in 0.9.9
