### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by hdtuan87** [seiginonakama/BlockCanaryEx#9]
Cannot build app when added library

`Error:Execution failed for task ':myproject:transformClassesWithBlockCanaryExForGPProductionDebug'.`
`> No such property: androidDependencies for class: com.android.build.gradle.internal.dependency.DependencyContainerImpl
Possible solutions: allAndroidDependencies`

**Comment by seiginonakama** [comment]
what's your 'com.android.tools.build:gradle' version? maybe there has some problem about compatibility.

**Comment by hdtuan87** [comment]
here

       classpath 'com.android.tools.build:gradle:2.3.1'
       classpath 'com.google.gms:google-services:3.0.0'

I use with google service

**Comment by seiginonakama** [comment]
I tried 'com.android.tools.build:gradle:2.3.1' but it worked fine in my project. Any information else ?about your gradle version or provide your build.gradle ?

**Comment by hdtuan87** [comment]
Yes.
module `build.gradle`

    apply plugin: 'com.android.application'
    apply plugin: 'blockcanaryex'

    android {
        compileSdkVersion 25
        buildToolsVersion "25.0.2"
        defaultConfig {
            applicationId "com.example.scorpion.testproject"
            minSdkVersion 15
            targetSdkVersion 25
            versionCode 1
            versionName "1.0"
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }

    task downloadFile {
        ant.get(src: 'https://moneylover.me/data/currency.json', dest: 'src/main/assets/', skipexisting: 'false')
    }
 
    dependencies {
        compile fileTree(include: ['*.jar'], dir: 'libs')
        compile 'com.android.support:appcompat-v7:25.3.1'
        compile 'com.android.support.constraint:constraint-layout:1.0.0-beta4'
        compile 'com.android.support:design:25.3.1'

        testCompile "org.robolectric:robolectric:3.3.2"
        testCompile "org.robolectric:shadows-support-v4:3.0"
        testCompile 'junit:junit:4.12'

        debugCompile 'com.letv.sarrsdesktop:BlockCanaryExJRT:0.9.8.2'
        releaseCompile 'com.letv.sarrsdesktop:BlockCanaryExJRTNoOp:0.9.8.2'
        testCompile 'com.letv.sarrsdesktop:BlockCanaryExJRTNoOp:0.9.8.2'
     }

top project `build.gradle`

    // Top-level build file where you can add configuration options common to all sub-projects/modules.

    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:2.3.1'
            classpath 'org.robolectric:robolectric-gradle-plugin:1.0.1'
            classpath 'com.letv.sarrsdesktop:BlockCanaryExPlugin:0.9.8.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        }
    }

     allprojects {
        repositories {
            jcenter()
        }
    }

    task clean(type: Delete) {
         delete rootProject.buildDir
    }

error log:

    Error:Execution failed for task ':app:transformClassesWithBlockCanaryExForDebug'.
    > No such property: androidDependencies for class: 
    com.android.build.gradle.internal.dependency.DependencyContainerImpl
    Possible solutions: allAndroidDependencies

**Comment by seiginonakama** [comment]
Weird, I use your build.gradle but also worked fine...O_O
could you try 'com.letv.sarrsdesktop:BlockCanaryExPlugin:0.9.8.2' ?

**Comment by hdtuan87** [comment]
OK it right. it worked.

Thank @seiginonakama

**Comment by NiaNingXue** [comment]
I have the similar error when applying "'com.letv.sarrsdesktop:BlockCanaryExPlugin:0.9.8.3" and version 0.9.8.2 is  ok

**Comment by seiginonakama** [comment]
@NiaNingXue can you tell me your com.android.tools.build:gradle version?

**Comment by NiaNingXue** [comment]
@seiginonakama  'com.android.tools.build:gradle:2.3.2'

**Comment by seiginonakama** [comment]
@NiaNingXue could you try "'com.letv.sarrsdesktop:BlockCanaryExPlugin:0.9.8.4", I fixed this issue in this version

**Comment by seiginonakama** [comment]
resolved in 0.9.9
